version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: deno
      shell: powershell.exe
    steps:
      - checkout
      - run: iwr https://deno.land/x/install/install.ps1 -useb | iex
      - run: deno -A test_win.ts