version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
      - run: iwr https://deno.land/x/install/install.ps1 -useb | iex
      - run: deno -A test_win.ts