version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
      - run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/denoland/deno_install/master/install.ps1 -OutFile ./install.ps1
      - run: ./install.ps1
      - run: deno -A test_win.ts